package com.ftn.sbnz.model.enums;

public enum AnimalBreed {
    LABRADOR_RETRIEVER, GERMAN_SHEPARD, GOLDEN_RETRIEVER, BULLDOG, POODLE, BEAGLE, CHIHUAHUA, ROTTWEILER, DALMATIAN,
    PUG, HUSKY, DOMESTIC_SHORTHAIR_CAT, SIAMESE_CAT, SPHYNX, BRITISH_SHORTHAIR_CAT, PERSIAN_CAT, CANARY, PIGEON, AFRICAN_GRAY_PARROT,
    BUDGERIGAR, COCKATIEL, TURTLE, GECKO, BALL_PYTHON, BEARDED_DRAGON, GUINEA_PIG, HAMSTER, TARANTULA, SMALL_FISH,
    BIG_FISH, BUNNY, DUTCH_DWARF_RABBIT, LIONHEAD
}
