package com.ftn.sbnz.model.enums;

public enum AnimalBreed {
    GERMAN_SHEPHERD, GOLDEN_RETRIEVER, BULLDOG, POODLE, BEAGLE, CHIHUAHUA, ROTTWEILER, DALMATIAN, LABRADOR_RETRIEVER,
    PUG, HUSKY, DOMESTIC_SHORTHAIR_CAT, SIAMESE_CAT, SPHYNX, BRITISH_SHORTHAIR_CAT, PERSIAN_CAT, CANARY, PIGEON, AFRICAN_GRAY_PARROT,
    BUDGERIGAR, COCKATIEL, TURTLE, GECKO, BALL_PYTHON, BEARDED_DRAGON, GUINEA_PIG, HAMSTER, TARANTULA, SMALL_FISH,
    BIG_FISH, BUNNY, DUTCH_DWARF_RABBIT, LIONHEAD
}
