package cep;

//ZADATAK 1 CEP VEZBE 2
/*rule "redirection if grounding fuckery"
    when
        $let1 : Flight(name == "let1")
        $let2 : Flight(name == "let2")
        $grounding_let2 : GroundingEvent(flight == $let2)
        $grounding_let1: GroundingEvent(flight == $let1, this after[0m, 3m] $grounding_let2)
    then
        $let1.redirect();
end

//ZADATAK 2 CEP VEZBE 2

rule "transaction duplication removal"
    when
        $t1 : Transaction($customer : customer, $amount : totalAmount)
        $t2 : Transaction(
         this != $t1,
         customer == $customer,
         totalAmount == $amount,
          this after[0s,15s] $t1)
    then
        System.out.println("Second transaction is a duplicate.");
end


rule "big boys with little playground"
    when
        $c1 : Customer($balance : balance)
        Number(doubleValue > $balance * 0.9) from accumulate (
        Transaction($amount : totalAmount,
                    totalAmount > 200.0,
                    customer == $c1) over window: time(90s),
        sum($amount)
        )
    then
        System.out.println("Some suspicious shit goin round here.");
end*/
